version: '3.7'
services:
  app:
    build:
      context: back_end/
      dockerfile: ./Dockerfile
    container_name: go-crud
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./back_end/src:/src
      - ./back_end/go:/go
    depends_on:
      - "db"
    env_file: ./.env
    command: sh -c "air"
  db:
    container_name: go-db
    image: mysql:8.0
    env_file: ./.env
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
