version: '3.7'
services:
  app:
    build:
      context: back_end/
      dockerfile: ./Dockerfile
    container_name: go-crud
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./back_end/code:/code
      - ./back_end/go:/go
      - ./back_end/build:/build
    depends_on:
      - "db"
    command: sh -c "air"
  db:
    container_name: go-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_db
      MYSQL_USER: go
      MYSQL_PASSWORD: go
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
