version: '3.7'
services:
  node:
    container_name: go-crud-node
    build:
      context: front/
      dockerfile: ./Dockerfile
    volumes:
      - ./front:/usr/src/front
      - ./.git:/usr/src/front/.git
    command: sh -c "yarn start"
    ports:
     - "3030:3000"
    stdin_open: true
  app:
    container_name: go-crud-app
    build:
      context: app/
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app/src:/src
      - ./app/go:/go
    depends_on:
      - "db"
    env_file: ./.env
    command: sh -c "air"
  db:
    container_name: go-db
    image: mysql:8.0
    env_file: ./.env
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
