-- +migrate Up
CREATE TABLE tasks (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(128) NOT NULL,
    category VARCHAR(128),
    explanation VARCHAR(128),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS tasks;