-- +migrate Up
CREATE TABLE tasks (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    title VARCHAR(128) NOT NULL,
    explanation VARCHAR(128),
    complete BOOLEAN NOT NULL DEFAULT FALSE,
    due_date   DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS tasks;